stages:
  - wrapped-pipeline
  - notify

pipeline-wrapper:
  stage: wrapped-pipeline
  allow_failure: true
  trigger:
    include: .nested-gitlab-ci.yml
    strategy: depend

persist:
  stage: notify
  script:
    - let pipeline_id=$CI_PIPELINE_ID+1
    - echo $pipeline_id
    - url="http://localhost:3333/api/pipelines/$pipeline_id?access_token=$PROJECT_TOKEN"
    - curl -X POST $url
