image: docker

services:
  - docker:dind

stages:
  - test
  - build
  - deploy

test:
  stage: test
  script:
    - let job_id=$CI_JOB_ID-1
    - echo $job_id
  tags:
    - cli


docker-build:
  stage: build
  before_script:
    - echo 'pruning docker images'
    - sudo docker image prune -f
    - sudo docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY_IMAGE
  script:
    - sudo docker-compose --env-file ./config/gitlab.env build --no-cache
  after_script:
    - curl -X POST http://localhost:3333/api/jobs/$CI_JOB_ID
  tags:
    - cli
  only:
    - master

deploy:
  stage: deploy
  before_script:
    - sudo docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY_IMAGE
  script:
    - sudo docker-compose --env-file ./config/gitlab.env up -d
  after_script:
    - curl -X POST http://localhost:3333/api/jobs/$CI_JOB_ID
  tags:
    - cli
  only:
    - master
