stages:
  - ng-build
  - docker-build
  - deploy

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA

ng-build:
  stage: ng-build
  before_script:
    - cd logchain-front
  script:
    - npm install -g @angular/cli
    - npm install --silent
    - ng build
  tags:
    - node
  artifacts:
    paths:
      - logchain-front/dist

docker-build:
  stage: docker-build
  only:
    - master
  tags:
    - cli
  before_script:
    - sudo docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY_IMAGE
  script:
    - echo $IMAGE_TAG
    - sudo docker build -t $IMAGE_TAG .
    - sudo docker push $IMAGE_TAG

deploy:
  stage: deploy
  only:
    - master
  tags:
    - cli
  before_script:
    - sudo docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY_IMAGE
  script:
    - sudo docker rm -f test-project && echo 'Suppression du container précédent'
    - sudo docker run -d --name test-project -p 8002:80 $IMAGE_TAG
