stages:
  - test
  - build
  - kill
  - deploy
  - clean

.back-setup:
  before_script:
    - cd logchain-back
    - npm install --silence
  except:
    - master

truffle-test:
  extends: .back-setup
  stage: test
  script:
    - npm install -g ganache-cli truffle
    - ganache-cli --host 127.0.0.1 --port 7545 &
    - truffle migrate --network test && truffle test
  tags:
    - node

.web-client-setup:
  before_script:
    - cd logchain-front
    - npm install --silence
  tags:
    - node
  except:
    - master

ng-build:
  extends: .web-client-setup
  stage: build
  script:
    - npm install -g @angular/cli --silence
    - ng build

.docker:
  tags:
    - cli
  only:
    - master

docker-build:
  extends: .docker
  stage: build
  before_script:
    - sudo docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY_IMAGE
  script:
    - sudo docker-compose --env-file $ENV_FILE build --no-cache

deploy:
  extends: .docker
  stage: deploy
  before_script:
    - sudo docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY_IMAGE
  script:
    - sudo docker-compose --env-file $ENV_FILE up -d

