stages:
  - test
  - build

.back-setup:
  before_script:
    - cd logchain-back
    - npm install --silence

truffle-test:
  extends: .back-setup
  stage: test
  script:
    - npm install -g ganache-cli truffle
    - ganache-cli --host 127.0.0.1 --port 7545 &
    - truffle migrate --network test && truffle test
  tags:
    - node

.web-client-setup:
  before_script:
    - cd logchain-front
    - npm install --silence
  tags:
    - node

ng-build:
  extends: .web-client-setup
  stage: build
  script:
    - npm install -g @angular/cli --silence
    - ng build

