version: '2' # specify docker-compose version

# Define the services/containers to be run
services:
  blockchain: # name of the third service
    image: "${CI_REGISTRY}/blockchain:latest"
    build: .
    ports:
      - "8545:8545" # specify port forwarding
    volumes:
      - ./ganache_data:/ganache_data
    hostname: blockchain
    entrypoint:
      - ganache-cli
      - --deterministic
      - --db=/ganache_data
      - --mnemonic
      - 'toward elephant meadow idea cup spawn grow strike feel pitch hold suit'
      - --networkId
      - '5777'
      - --hostname
      - '0.0.0.0'

  client: # name of the first service
    image: "${CI_REGISTRY}/front:latest"
    build: logchain-front # specify the directory of the Dockerfile
    links:
      - server
    depends_on:
      - server
    ports:
      - "4200:80" # specify port forwarding

  server: #name of the second service
    image: "${CI_REGISTRY}/back:latest"
    build: logchain-back # specify the directory of the Dockerfile
    ports:
      - "3333:3333" #specify ports forwarding
    hostname: api
    depends_on:
      - blockchain
    restart: always
    environment:
      - GITLAB_API_URL=$GITLAB_API_URL
      - API_PORT=$API_PORT
      - PROJECT_TOKEN=$PROJECT_TOKEN
      - PROJECT_ID=$PROJECT_ID
      - BLOCKCHAIN_ADDRESS=$BLOCKCHAIN_ADDRESS
